export const productCategoryBySlug: Record<string, string> = {
  "precision-blade-sharpening": "Sharpening Services",
  "arden-router-bits": "Featured Brand",
  "power-tools": "Power Tools",
  "power-tool-accessories": "Power Tool Accessories",
  "industrial-drills": "Power Tools",
  "pneumatic-tools": "Pneumatic Tools",
  "pneumatic-brad-nailer-f50": "Pneumatic Tools",
  "pneumatic-brad-nailer-f32": "Pneumatic Tools",
  "pneumatic-stapler-1013j": "Pneumatic Tools",
  "pneumatic-stapler-422j": "Pneumatic Tools",
  "pneumatic-screwdrivers": "Pneumatic Tools",
  routers: "Power Tools",
  grinders: "Power Tools",
  planers: "Power Tools",
  "jig-saws": "Power Tools",
  "circular-saws": "Power Tools",
  "screw-drivers": "Power Tools",
  "tyre-buffing-blades": "Tyre Rebuilding Tools",
  "r6-refills": "Tyre Rebuilding Tools",
  "woodworking-tools": "Woodworking Tools",
  "stainless-steel-tube-handles": "Woodworking Tools",
  "drawer-runners": "Woodworking Tools",
  magnets: "Woodworking Tools",
  "drawer-lockers": "Woodworking Tools",
  "hinges-set": "Woodworking Tools",
  "shelf-supports": "Woodworking Tools",
  "sanding-rolls-belts": "Woodworking Tools",
  "router-bits-boring-bits": "Woodworking Tools",
  "tongue-groove-cutter-set": "Woodworking Tools",
  "mortising-chisel-bit": "Woodworking Tools",
  "hand-planer-blades": "Hand Tool Accessories",
  "nail-pins": "Pneumatic Tool Accessories",
  "stapler-pins": "Pneumatic Tool Accessories",
  "band-saw-blades": "Power Tool Accessories",
  "boring-bits": "Power Tool Accessories",
  "power-tool-circular-saw-blades": "Power Tool Accessories",
  "planer-blades": "Power Tool Accessories",
  "router-bits": "Power Tool Accessories",
  "screw-bits-bosch": "Power Tool Accessories",
  "tyre-rebuilding-tools": "Industrial Equipment",
  "maintenance-kits": "Accessories",
  "technician-toolkits": "Workshop Essentials",
  "rebuild-wheel-systems": "Industrial Equipment",
  "tct-blades": "Cutting Tools",
  "hss-blades": "Cutting Tools",
};

export const productSearchKeywordsBySlug: Record<string, string> = {
  "precision-blade-sharpening":
    "service sharpening automated blades tools tct hss polythene winder metal plate reel crusher paper planer circular profile grooving finger joint hinge boring",
  "arden-router-bits":
    "arden routing tools router bits precision technology taiwan woodworking sole importer",
  "power-tools": "power tools routers drills grinders planers jig saws circular saws screw drivers",
  "power-tool-accessories":
    "power tool accessories band saw blades boring bits circular saw blades mortising chisel bit planer blades router bits sanding belts sanding rolls screw bits bosch tongue groove cutter set",
  "industrial-drills": "power tools drills bosch skill chinese brands 10mm speed control",
  "pneumatic-tools":
    "pneumatic tools brad nailer f50 f32 stapler 1013j 422j screwdrivers air tools nail pins stapler pins workshop production",
  "pneumatic-brad-nailer-f50": "pneumatic brad nailer yugo f50 nail pins air tool",
  "pneumatic-brad-nailer-f32": "pneumatic brad nailer yugo f32 nail pins air tool",
  "pneumatic-stapler-1013j": "pneumatic stapler yugo 1013j stapler pins air tool",
  "pneumatic-stapler-422j": "pneumatic stapler yugo 422j stapler pins air tool",
  "pneumatic-screwdrivers": "pneumatic screwdrivers air screwdriver drilling 3/8 10mm",
  routers: "power tools routers 12mm chuck woodworking routing machine",
  grinders: "power tools grinders 100mm 115mm angle grinder",
  planers: "power tools planers 80mm 136mm planer machine",
  "jig-saws": "power tools jig saw jigsaw cutting 65mm",
  "circular-saws": "power tools circular saws 185mm 235mm",
  "screw-drivers": "power tools screw drivers cordless screwdriver drill",
  "tyre-buffing-blades": "tyre rebuilding tyre buffing blades uniform surface texture",
  "r6-refills": "tyre rebuilding r6 refills r5 r6 rasps rubber removal",
  "woodworking-tools":
    "woodworking tools drawer runners hinges shelf supports sanding rolls belts router bits boring bits tongue groove mortising chisel hand planer blades",
  "stainless-steel-tube-handles": "woodworking stainless steel tube handles furniture hardware",
  "drawer-runners": "woodworking drawer runners furniture hardware",
  magnets: "woodworking magnets furniture hardware cabinet hardware",
  "drawer-lockers": "woodworking drawer lockers furniture locks",
  "hinges-set": "woodworking hinges set furniture hardware",
  "shelf-supports": "woodworking shelf supports cabinet hardware",
  "sanding-rolls-belts": "woodworking sanding rolls sanding belts abrasive accessories",
  "router-bits-boring-bits": "woodworking router bits boring bits routing drilling",
  "tongue-groove-cutter-set": "woodworking tongue groove cutter set profile cutter",
  "mortising-chisel-bit": "woodworking mortising chisel bit square hole drill",
  "hand-planer-blades": "hand tools accessories hand planer blades planer blade carbon",
  "nail-pins": "pneumatic accessories nail pins brad nailer f50 f32",
  "stapler-pins": "pneumatic accessories stapler pins 1013j 422j",
  "band-saw-blades": "power tool accessories band saw blades cutting blades",
  "boring-bits": "power tool accessories boring bits hinge boring drill bits",
  "power-tool-circular-saw-blades": "power tool accessories circular saw blades tct cutting",
  "planer-blades": "power tool accessories planer blades carbon blades",
  "router-bits": "power tool accessories router bits arden woodworking",
  "screw-bits-bosch": "power tool accessories screw bits bosch screwdriver bits",
  "tyre-rebuilding-tools": "industrial equipment tyre rebuilding buffing blades r6 refills",
  "maintenance-kits": "maintenance kits workshop consumables servicing tool care",
  "technician-toolkits": "technician toolkits portable service maintenance hand tools",
  "rebuild-wheel-systems": "rebuild wheel systems restoration workshop tooling tyre rebuilding",
  "tct-blades": "tct blades tungsten carbide tipped circular saw sharpening",
  "hss-blades": "hss blades high speed steel paper cutting carbon sharpening",
};
